---
title: "385HW7EX"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("RSQLite")
install.packages("DBI")
```


```{r}
vehicledata = DBI::dbConnect(RSQLite::SQLite(), "vehicledata.sqlite")
dbDisconnect(vehicledata)
unlink("vehicledata.sqlite")
vd = dbConnect(RSQLite::SQLite(), "")
```

```{sql, connection = vd}
CREATE TABLE vehicles (make TEXT, model TEXT, trim TEXT, hp INTEGER)
```
```{sql, connection = vd}
INSERT INTO vehicles VALUES ("Chevrolet", "Crovette", "Z06", 640), ("Ford","Mustang", "GT", 480), ("Mazda", "Miata", "RF", 185)
```


```{sql, connection = vd}
INSERT INTO vehicles VALUES ("Ford", "Focus", "ST", 250), ("Volkswagen", "Golf", "GTI", "220"), ("Dodge", "Challenger", "ScatPak", 485), ("Dodge", "Challenger", "Hellcat", 707), ("Dodge", "Challenger", "Hellcat Redeye", 797), ("Jeep", "Grand Cherokee", "TrackHawk", 707), ("Honda", "Civic", "Si", 202), ("Honda", "Civic", "Type R", 303)
```
```{sql, connection = vd}
CREATE TABLE cardata (id INTEGER, make TEXT, model TEXT, trim TEXT, hp INTEGER, cylinders INTEGER)
```


```{sql, connection = vd}
INSERT INTO cardata VALUES (1, "Ford", "Focus", "ST", 250, 4), (2, "Volkswagen", "Golf", "GTI", "220", 4), (3, "Dodge", "Challenger", "ScatPak", 485,8), (4, "Dodge", "Challenger", "Hellcat", 707,8), (5, "Dodge", "Challenger", "Hellcat Redeye", 797,8), (6, "Jeep", "Grand Cherokee", "TrackHawk", 707,8), (7, "Honda", "Civic", "Si", 202,4), (8, "Honda", "Civic", "Type R", 303,4)

```
```{sql, connection = vd}
INSERT INTO cardata VALUES(9, "Jeep", "Grand Cherokee", "Limited", 280, 6), (10, "Jeep", "Wrangler", "Unlimited", 280, 6), (11, "Chevrolet", "Camaro","ZL1", 650, 8), (12, "Chevrolet", "Camaro", "SS", 455, 8), (13, "Dodge", "Challenger", "GT", 305, 6),(14, "Ford","Mustang", "GT350", 528, 8), (15, "Audi", "RS3", "RS3", 394, 5), (16, "Audi", "RS5", "RS5", 444, 6), (17, "Chevrolet", "Equinox","Premier", 165, 4)
```

```{sql, connection = vd}
SELECT * FROM cardata
```

```{sql, connection = vd}
CREATE TABLE aspiration (id INTEGER, aspiration_type TEXT)
```

```{sql, connection = vd}
SELECT * FROM cardata

```

```{sql, connection = vd}
INSERT INTO cardata VALUES (18, "Buick", "Regal", "GS", 310, 6), (19, "Buick", "Enclave", "Premier", 310, 6), (20, "Cadillac", "CTS", "V", 640, 8), (21, "Cadillac", "ATS", "V", 464, 6), (22, "Chevrolet", "SS", "NA", 415, 8)
```
```{sql, connection = vd}
SELECT * FROM cardata

```



```{sql, connection = vd}
INSERT INTO aspiration VALUES (1, "Turbocharged"), (2, "Turbocharged"), (3, "NA"), (4, "Supercharged"), (5, "Supercharged"), (6, "Supercharged"), (7, "NA"), (8, "Turbocharged"), (9, "NA"), (10, "NA"), (11, "Supercharged"), (12, "NA"), (13, "NA"), (14, "NA"), (15, "Turbocharged"), (16, "NA"),(17,"NA")
```
```{r}
```

```{sql, connection = vd}
SELECT * FROM aspiration
```

```{sql, connection = vd}
SELECT cardata.id, cardata.make, cardata.model, cardata.trim, cardata.hp, cardata.cylinders,aspiration.aspiration_type
FROM cardata
INNER JOIN aspiration
ON cardata.id = aspiration.id
```
```{sql, connection = vd}
SELECT AVG(hp) AS average_horsepower FROM cardata

```
```{sql, connection = vd}
SELECT * FROM cardata

```



```{sql, connection = vd}
INSERT INTO cardata VALUES(23, "Toyota", "Camry", "XLE V6", 301, 6), (24, "Toyota", "Land Cruiser", "NA", 381, 8), (25, "Toyota", "4Runner", "Base", 270, 6), (26, "Cadillac", "Escalade", "Premium Luxury", 420, 8)
```

```{sql, connection = vd}
INSERT INTO cardata VALUES (27, "Kia", "Stinger", "GT", 365, 6), (28, "Genesis", "G70", "Top", 365, 6)
```

```{sql, connection = vd}
SELECT * FROM cardata
```

